### ISSUE TITLE
刚测试一个问题

### ISSUE THREAD

**Issue by Troll4it** [lygttpod/AndroidCustomView#1]
java.lang.NoSuchMethodError: android.animation.ValueAnimator.pause
                                                                               at com.allen.androidcustomview.widget.WaveViewByBezier.pauseAnimation(WaveViewByBezier.java:190)
                                                                               at com.allen.androidcustomview.WaveByBezierActivity.onPause(WaveByBezierActivity.java:28)
                                                                               at android.app.Activity.performPause(Activity.java:5206)
                                                                               at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1226)
                                                                               at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3002)
                                                                               at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2971)
                                                                               at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2949)
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1251)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:137)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                               at dalvik.system.NativeStart.main(Native Method)
05-04 21:04:49.805 1900-1900/com.allen.androidcustomview I/Process: Sending signal. PID: 1900 SIG: 9

**Comment by lygttpod** [comment]
麻烦描述一下错误出现的操作，是必现还是某个具体操作，我这边项目demo跑起来是没有问题的

**Comment by Troll4it** [comment]
点击进入水波扩散效果界面，在点击返回界面必崩。。不过你的动画还是写的66666

**Comment by Troll4it** [comment]
贝塞尔曲线实现也是

**Comment by lygttpod** [comment]
机型及版本号多少

**Comment by Troll4it** [comment]
我用是逍遥模拟器

**Comment by Troll4it** [comment]
你好，分享下解决方案吗

**Comment by lygttpod** [comment]
你用真机或者换个模拟器试试，我这边用Genymotion 或者夜神模拟器和真机都是没问题的，没用过逍遥模拟器。。。，再好的模拟器都不如真机测试实在，哈哈
